### ISSUE TITLE
docker-compose重启容器，mysql容器会失败，导致数据丢失

### ISSUE THREAD

**Issue by nibiwodong** [ztosec/hunter#10]
在虚拟机里执行docker-compose up -d
启动容器成功，此时直接重启linux服务器，启动后，发现容器都已经不在了，再次执行docker-compose up -d，发现如下报错，仍可以启动成功，但mysql数据丢了。日志如下：
hunter-admin-gui    | 
hunter-admin-gui    | > hunter-antd-user-v1.1@0.1.0 build /home/hunter/HunterAdminGui
hunter-admin-gui    | > node scripts/build.js
hunter-admin-gui    | 
hunter-admin-api    | setp1:修改rabbitmq配置文件
hunter-admin-api    | setp2:修改mysql配置文件
hunter-admin-api    | setp3:修改redis配置文件
hunter-admin-api    | setp4:初始化数据库中数据
hunter-admin-api    | 初始化数据库失败,5秒后自动重试
hunter-redis        | setp1:修改redis配置文件密码
hunter-redis        | /usr/bin/init-redis.sh: line 2: [1: command not found
hunter-redis        | setp2:启动redis
hunter-redis        | 9:C 17 Jan 10:27:11.753 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
hunter-redis        | 9:C 17 Jan 10:27:11.767 # Redis version=4.0.6, bits=64, commit=00000000, modified=0, pid=9, just started
hunter-redis        | 9:C 17 Jan 10:27:11.767 # Configuration loaded
hunter-redis        | setp3:检查redis-server启动状态
hunter-redis        | setp4:redis-server成功启动
hunter-mysql        | step1:检查mysql-server启动状态
hunter-mysql        | 2020-01-17 10:27:11+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.28-1debian9 started.
hunter-mysql        | 2020-01-17 10:27:12+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
hunter-mysql        | 2020-01-17 10:27:12+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.28-1debian9 started.
hunter-mysql        | 2020-01-17 10:27:13+00:00 [Note] [Entrypoint]: Initializing database files
hunter-mysql        | 2020-01-17T10:27:13.376809Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
hunter-mysql        | 2020-01-17T10:27:13.946292Z 0 [Warning] InnoDB: New log files created, LSN=45790
hunter-mysql        | 2020-01-17T10:27:14.039970Z 0 [Warning] InnoDB: Creating foreign key constraint system tables.
hunter-mysql        | 2020-01-17T10:27:14.112555Z 0 [Warning] No existing UUID has been found, so we assume that this is the first time that this server has been started. Generating a new UUID: ed919837-3913-11ea-ab3b-0242ac120004.
hunter-mysql        | 2020-01-17T10:27:14.122492Z 0 [Warning] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.
hunter-mysql        | 2020-01-17T10:27:15.803930Z 0 [Warning] CA certificate ca.pem is self signed.
hunter-mysql        | 2020-01-17T10:27:16.113042Z 1 [Warning] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
hunter-sense        | ('CREATE TABLE IF NOT EXISTS "user" ("id" INTEGER NOT NULL PRIMARY KEY, "username" TEXT, "password" TEXT, "token" TEXT)', [])
hunter-sense        | No connection available in pool.
hunter-sense        | Created new connection 140561788450608.
hunter-sense        | ('INSERT INTO "user" ("username", "password", "token") VALUES (?, ?, ?)', ['admin', 'admin888', 'hunter-log-token'])
hunter-sense        | ('CREATE TABLE IF NOT EXISTS "requestlog" ("id" INTEGER NOT NULL PRIMARY KEY, "ip" TEXT NOT NULL, "port" TEXT NOT NULL, "protocol" TEXT, "time_str" DATETIME NOT NULL, "plugin" TEXT NOT NULL, "recv_data" TEXT NOT NULL, "time_stamp" REAL)', [])
hunter-sense        | ('CREATE TABLE IF NOT EXISTS "requestlogdup" ("id" INTEGER NOT NULL PRIMARY KEY, "ip" TEXT NOT NULL, "port" TEXT NOT NULL, "protocol" TEXT, "time_str" DATETIME NOT NULL, "plugin" TEXT NOT NULL, "recv_data" TEXT NOT NULL, "time_stamp" REAL)', [])
hunter-sense        | ('CREATE TABLE IF NOT EXISTS "systemsetting" ("id" INTEGER NOT NULL PRIMARY KEY, "socket_port" INTEGER NOT NULL, "socket_switch" INTEGER NOT NULL, "fake_root_domain" TEXT NOT NULL, "ns1domain" TEXT NOT NULL, "ns2domain" TEXT NOT NULL, "server_ip" TEXT NOT NULL, "dns_switch" INTEGER NOT NULL)', [])
hunter-sense        | ('INSERT INTO "systemsetting" ("socket_port", "socket_switch", "fake_root_domain", "ns1domain", "ns2domain", "server_ip", "dns_switch") VALUES (?, ?, ?, ?, ?, ?, ?)', [7799, False, 'xxx.com', 'ns1.xxx.com', 'ns1.xxx.com', 'xx.xx.xx.xx', False])
hunter-sense        | ('SELECT "t1"."id", "t1"."username", "t1"."password", "t1"."token" FROM "user" AS "t1"', [])
hunter-sense        | Returning 140561788450608 to pool.
hunter-sense        | username:admin,passwor:admin888,token:hunter-log-token
hunter-sense        | 初始化账号密码成功
hunter-sense        | nginx启动成功
hunter-sense        | root          17       1  0 18:27 ?        00:00:00 /usr/bin/python3 /usr/local/bin/supervisord -c /home/app/supervisor.conf
hunter-sense        | supervisord启动成功
hunter-rabbitmq     | root           1 25.6  0.1  20120  3360 ?        Ss   10:27   0:00 bash /usr/local/bin/init-rabbitmq.sh admin rabbitmq123456
hunter-rabbitmq     | root           6  0.0  0.0   4624  1712 ?        S    10:27   0:00 /bin/sh /opt/rabbitmq/sbin/rabbitmq-server --detached
hunter-rabbitmq     | root           8  0.0  0.0  13208   960 ?        S    10:27   0:00 grep rabbitmq
hunter-rabbitmq     | root          29  0.0  0.0   4624   128 ?        S    10:27   0:00 /bin/sh /opt/rabbitmq/sbin/rabbitmq-server --detached
hunter-rabbitmq     | step1:检查rabbitmq-server启动状态
hunter-mysql        | 2020-01-17 10:27:26+00:00 [Note] [Entrypoint]: Database files initialized
hunter-mysql        | 2020-01-17 10:27:26+00:00 [Note] [Entrypoint]: Starting temporary server
hunter-mysql        | 2020-01-17 10:27:26+00:00 [Note] [Entrypoint]: Waiting for server startup
hunter-mysql        | 2020-01-17T10:27:27.154563Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
hunter-mysql        | 2020-01-17T10:27:27.157724Z 0 [Note] mysqld (mysqld 5.7.28) starting as process 86 ...
hunter-mysql        | 2020-01-17T10:27:27.170343Z 0 [Note] InnoDB: PUNCH HOLE support available
hunter-mysql        | 2020-01-17T10:27:27.170437Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
hunter-mysql        | 2020-01-17T10:27:27.170452Z 0 [Note] InnoDB: Uses event mutexes
hunter-mysql        | 2020-01-17T10:27:27.170498Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
hunter-mysql        | 2020-01-17T10:27:27.170509Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
hunter-mysql        | 2020-01-17T10:27:27.170520Z 0 [Note] InnoDB: Using Linux native AIO
hunter-mysql        | 2020-01-17T10:27:27.171786Z 0 [Note] InnoDB: Number of pools: 1
hunter-mysql        | 2020-01-17T10:27:27.172058Z 0 [Note] InnoDB: Using CPU crc32 instructions
hunter-mysql        | 2020-01-17T10:27:27.180302Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
hunter-mysql        | 2020-01-17T10:27:27.211728Z 0 [Note] InnoDB: Completed initialization of buffer pool
hunter-mysql        | 2020-01-17T10:27:27.220866Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
hunter-mysql        | 2020-01-17T10:27:27.265923Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
hunter-mysql        | 2020-01-17T10:27:27.304315Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
hunter-mysql        | 2020-01-17T10:27:27.304471Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
hunter-mysql        | 2020-01-17T10:27:27.385694Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
hunter-mysql        | 2020-01-17T10:27:27.388406Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
hunter-mysql        | 2020-01-17T10:27:27.388915Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
hunter-mysql        | 2020-01-17T10:27:27.389928Z 0 [Note] InnoDB: 5.7.28 started; log sequence number 2628236
hunter-mysql        | 2020-01-17T10:27:27.391006Z 0 [Note] Plugin 'FEDERATED' is disabled.
hunter-mysql        | 2020-01-17T10:27:27.398862Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
hunter-mysql        | 2020-01-17T10:27:27.405623Z 0 [Note] InnoDB: Buffer pool(s) load completed at 200117 10:27:27
hunter-mysql        | 2020-01-17T10:27:27.408514Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
hunter-mysql        | 2020-01-17T10:27:27.408578Z 0 [Note] Skipping generation of SSL certificates as certificate files are present in data directory.
hunter-mysql        | 2020-01-17T10:27:27.411798Z 0 [Warning] CA certificate ca.pem is self signed.
hunter-mysql        | 2020-01-17T10:27:27.411871Z 0 [Note] Skipping generation of RSA key pair as key files are present in data directory.
hunter-mysql        | 2020-01-17T10:27:27.416945Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
hunter-mysql        | 2020-01-17T10:27:27.451248Z 0 [Note] Event Scheduler: Loaded 0 events
hunter-mysql        | 2020-01-17T10:27:27.451664Z 0 [Note] mysqld: ready for connections.
hunter-mysql        | Version: '5.7.28'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  MySQL Community Server (GPL)
hunter-mysql        | 2020-01-17 10:27:28+00:00 [Note] [Entrypoint]: Temporary server started.
hunter-mysql        | Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
hunter-mysql        | Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
hunter-admin-api    | 初始化数据库失败,5秒后自动重试
hunter-admin-gui    | Creating an optimized production build...
hunter-mysql        | Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
hunter-mysql        | Warning: Unable to load '/usr/share/zoneinfo/zone1970.tab' as time zone. Skipping it.
hunter-mysql        | 
hunter-mysql        | 2020-01-17 10:27:35+00:00 [Note] [Entrypoint]: Stopping temporary server
hunter-mysql        | 2020-01-17T10:27:35.375542Z 0 [Note] Giving 0 client threads a chance to die gracefully
hunter-mysql        | 2020-01-17T10:27:35.375595Z 0 [Note] Shutting down slave threads
hunter-mysql        | 2020-01-17T10:27:35.375607Z 0 [Note] Forcefully disconnecting 0 remaining clients
hunter-mysql        | 2020-01-17T10:27:35.375622Z 0 [Note] Event Scheduler: Purging the queue. 0 events
hunter-mysql        | 2020-01-17T10:27:35.375728Z 0 [Note] Binlog end
hunter-mysql        | 2020-01-17T10:27:35.376577Z 0 [Note] Shutting down plugin 'ngram'
hunter-mysql        | 2020-01-17T10:27:35.376600Z 0 [Note] Shutting down plugin 'partition'
hunter-mysql        | 2020-01-17T10:27:35.376609Z 0 [Note] Shutting down plugin 'BLACKHOLE'
hunter-mysql        | 2020-01-17T10:27:35.376618Z 0 [Note] Shutting down plugin 'ARCHIVE'
hunter-mysql        | 2020-01-17T10:27:35.376625Z 0 [Note] Shutting down plugin 'PERFORMANCE_SCHEMA'
hunter-mysql        | 2020-01-17T10:27:35.376669Z 0 [Note] Shutting down plugin 'MRG_MYISAM'
hunter-mysql        | 2020-01-17T10:27:35.376678Z 0 [Note] Shutting down plugin 'MyISAM'
hunter-mysql        | 2020-01-17T10:27:35.376697Z 0 [Note] Shutting down plugin 'INNODB_SYS_VIRTUAL'
hunter-mysql        | 2020-01-17T10:27:35.376708Z 0 [Note] Shutting down plugin 'INNODB_SYS_DATAFILES'
hunter-mysql        | 2020-01-17T10:27:35.376715Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLESPACES'
hunter-mysql        | 2020-01-17T10:27:35.376721Z 0 [Note] Shutting down plugin 'INNODB_SYS_FOREIGN_COLS'
hunter-mysql        | 2020-01-17T10:27:35.376728Z 0 [Note] Shutting down plugin 'INNODB_SYS_FOREIGN'
hunter-mysql        | 2020-01-17T10:27:35.376735Z 0 [Note] Shutting down plugin 'INNODB_SYS_FIELDS'
hunter-mysql        | 2020-01-17T10:27:35.376742Z 0 [Note] Shutting down plugin 'INNODB_SYS_COLUMNS'
hunter-mysql        | 2020-01-17T10:27:35.376749Z 0 [Note] Shutting down plugin 'INNODB_SYS_INDEXES'
hunter-mysql        | 2020-01-17T10:27:35.376756Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLESTATS'
hunter-mysql        | 2020-01-17T10:27:35.376762Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLES'
hunter-mysql        | 2020-01-17T10:27:35.376769Z 0 [Note] Shutting down plugin 'INNODB_FT_INDEX_TABLE'
hunter-mysql        | 2020-01-17T10:27:35.376776Z 0 [Note] Shutting down plugin 'INNODB_FT_INDEX_CACHE'
hunter-mysql        | 2020-01-17T10:27:35.376783Z 0 [Note] Shutting down plugin 'INNODB_FT_CONFIG'
hunter-mysql        | 2020-01-17T10:27:35.376790Z 0 [Note] Shutting down plugin 'INNODB_FT_BEING_DELETED'
hunter-mysql        | 2020-01-17T10:27:35.376798Z 0 [Note] Shutting down plugin 'INNODB_FT_DELETED'
hunter-mysql        | 2020-01-17T10:27:35.376805Z 0 [Note] Shutting down plugin 'INNODB_FT_DEFAULT_STOPWORD'
hunter-mysql        | 2020-01-17T10:27:35.376812Z 0 [Note] Shutting down plugin 'INNODB_METRICS'
hunter-mysql        | 2020-01-17T10:27:35.376819Z 0 [Note] Shutting down plugin 'INNODB_TEMP_TABLE_INFO'
hunter-mysql        | 2020-01-17T10:27:35.376826Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_POOL_STATS'
hunter-mysql        | 2020-01-17T10:27:35.376833Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE_LRU'
hunter-mysql        | 2020-01-17T10:27:35.376841Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE'
hunter-mysql        | 2020-01-17T10:27:35.376849Z 0 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX_RESET'
hunter-mysql        | 2020-01-17T10:27:35.376856Z 0 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX'
hunter-mysql        | 2020-01-17T10:27:35.376864Z 0 [Note] Shutting down plugin 'INNODB_CMPMEM_RESET'
hunter-mysql        | 2020-01-17T10:27:35.376872Z 0 [Note] Shutting down plugin 'INNODB_CMPMEM'
hunter-mysql        | 2020-01-17T10:27:35.376879Z 0 [Note] Shutting down plugin 'INNODB_CMP_RESET'
hunter-mysql        | 2020-01-17T10:27:35.376886Z 0 [Note] Shutting down plugin 'INNODB_CMP'
hunter-mysql        | 2020-01-17T10:27:35.376893Z 0 [Note] Shutting down plugin 'INNODB_LOCK_WAITS'
hunter-mysql        | 2020-01-17T10:27:35.376901Z 0 [Note] Shutting down plugin 'INNODB_LOCKS'
hunter-mysql        | 2020-01-17T10:27:35.376908Z 0 [Note] Shutting down plugin 'INNODB_TRX'
hunter-mysql        | 2020-01-17T10:27:35.376915Z 0 [Note] Shutting down plugin 'InnoDB'
hunter-mysql        | 2020-01-17T10:27:35.383011Z 0 [Note] InnoDB: FTS optimize thread exiting.
hunter-mysql        | 2020-01-17T10:27:35.385560Z 0 [Note] InnoDB: Starting shutdown...
hunter-mysql        | 2020-01-17T10:27:35.488060Z 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
hunter-mysql        | 2020-01-17T10:27:35.488504Z 0 [Note] InnoDB: Buffer pool(s) dump completed at 200117 10:27:35
hunter-mysql        | 2020-01-17T10:27:37.153512Z 0 [Note] InnoDB: Shutdown completed; log sequence number 12440259
hunter-mysql        | 2020-01-17T10:27:37.158995Z 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
hunter-mysql        | 2020-01-17T10:27:37.164924Z 0 [Note] Shutting down plugin 'MEMORY'
hunter-mysql        | 2020-01-17T10:27:37.165133Z 0 [Note] Shutting down plugin 'CSV'
hunter-mysql        | 2020-01-17T10:27:37.165289Z 0 [Note] Shutting down plugin 'sha256_password'
hunter-mysql        | 2020-01-17T10:27:37.173732Z 0 [Note] Shutting down plugin 'mysql_native_password'
hunter-mysql        | 2020-01-17T10:27:37.174331Z 0 [Note] Shutting down plugin 'binlog'
hunter-mysql        | 2020-01-17T10:27:37.182246Z 0 [Note] mysqld: Shutdown complete
hunter-mysql        | 
hunter-mysql        | 2020-01-17 10:27:37+00:00 [Note] [Entrypoint]: Temporary server stopped
hunter-mysql        | 
hunter-mysql        | 2020-01-17 10:27:37+00:00 [Note] [Entrypoint]: MySQL init process done. Ready for start up.
hunter-mysql        | 
hunter-mysql        | 2020-01-17T10:27:37.703018Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
hunter-mysql        | 2020-01-17T10:27:37.712524Z 0 [Note] mysqld (mysqld 5.7.28) starting as process 10 ...
hunter-mysql        | 2020-01-17T10:27:37.722525Z 0 [Note] InnoDB: PUNCH HOLE support available
hunter-mysql        | 2020-01-17T10:27:37.722655Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
hunter-mysql        | 2020-01-17T10:27:37.722678Z 0 [Note] InnoDB: Uses event mutexes
hunter-mysql        | 2020-01-17T10:27:37.722825Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
hunter-mysql        | 2020-01-17T10:27:37.722844Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
hunter-mysql        | 2020-01-17T10:27:37.722856Z 0 [Note] InnoDB: Using Linux native AIO
hunter-mysql        | 2020-01-17T10:27:37.724527Z 0 [Note] InnoDB: Number of pools: 1
hunter-mysql        | 2020-01-17T10:27:37.725833Z 0 [Note] InnoDB: Using CPU crc32 instructions
hunter-mysql        | 2020-01-17T10:27:37.729185Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
hunter-mysql        | 2020-01-17T10:27:37.763079Z 0 [Note] InnoDB: Completed initialization of buffer pool
hunter-mysql        | 2020-01-17T10:27:37.768831Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
hunter-mysql        | 2020-01-17T10:27:37.784191Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
hunter-mysql        | 2020-01-17T10:27:37.880410Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
hunter-mysql        | 2020-01-17T10:27:37.885118Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
hunter-mysql        | 2020-01-17T10:27:37.924798Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
hunter-mysql        | 2020-01-17T10:27:37.926418Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
hunter-mysql        | 2020-01-17T10:27:37.926446Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
hunter-mysql        | 2020-01-17T10:27:37.927606Z 0 [Note] InnoDB: Waiting for purge to start
hunter-mysql        | 2020-01-17T10:27:37.985968Z 0 [Note] InnoDB: 5.7.28 started; log sequence number 12440259
hunter-mysql        | 2020-01-17T10:27:37.986834Z 0 [Note] Plugin 'FEDERATED' is disabled.
hunter-mysql        | 2020-01-17T10:27:37.996068Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
hunter-mysql        | 2020-01-17T10:27:38.024800Z 0 [Note] InnoDB: Buffer pool(s) load completed at 200117 10:27:38
hunter-mysql        | 2020-01-17T10:27:38.046356Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
hunter-mysql        | 2020-01-17T10:27:38.047624Z 0 [Note] Skipping generation of SSL certificates as certificate files are present in data directory.
hunter-mysql        | 2020-01-17T10:27:38.053610Z 0 [Warning] CA certificate ca.pem is self signed.
hunter-mysql        | 2020-01-17T10:27:38.055997Z 0 [Note] Skipping generation of RSA key pair as key files are present in data directory.
hunter-mysql        | 2020-01-17T10:27:38.058027Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
hunter-mysql        | 2020-01-17T10:27:38.058342Z 0 [Note] IPv6 is available.
hunter-mysql        | 2020-01-17T10:27:38.060762Z 0 [Note]   - '::' resolves to '::';
hunter-mysql        | 2020-01-17T10:27:38.061720Z 0 [Note] Server socket created on IP: '::'.
hunter-mysql        | 2020-01-17T10:27:38.074447Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
hunter-mysql        | 2020-01-17T10:27:38.138319Z 0 [Note] Event Scheduler: Loaded 0 events
hunter-mysql        | 2020-01-17T10:27:38.138973Z 0 [Note] mysqld: ready for connections.
hunter-mysql        | Version: '5.7.28'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
hunter-mysql        | 2020-01-17T10:27:39.328120Z 2 [Note] Unknown database 'hunter'
hunter-admin-api    | 初始化数据库失败,5秒后自动重试
hunter-mysql        | MySQL started successfully
hunter-mysql        | step2:mysql-server成功启动
hunter-mysql        | step3:开始新建外链账号
hunter-mysql        | mysql: [Warning] Using a password on the command line interface can be insecure.
hunter-mysql        | step4:新建外链账号成功
hunter-mysql        | step5:需要运行python init_table.py初始化数据库脚本
hunter-admin-api    | [2020-01-17 10:27:46] [INFO] reload local plugins
hunter-rabbitmq     | 2020-01-17 10:27:46.994 [info] <0.8.0> Feature flags: list of feature flags found:
hunter-rabbitmq     | 2020-01-17 10:27:46.998 [info] <0.8.0> Feature flags:   [ ] drop_unroutable_metric
hunter-rabbitmq     | 2020-01-17 10:27:47.000 [info] <0.8.0> Feature flags:   [ ] empty_basic_get_metric
hunter-rabbitmq     | 2020-01-17 10:27:47.000 [info] <0.8.0> Feature flags:   [ ] implicit_default_bindings
hunter-rabbitmq     | 2020-01-17 10:27:47.000 [info] <0.8.0> Feature flags:   [ ] quorum_queue
hunter-rabbitmq     | 2020-01-17 10:27:47.000 [info] <0.8.0> Feature flags:   [ ] virtual_host_metadata
hunter-rabbitmq     | 2020-01-17 10:27:47.000 [info] <0.8.0> Feature flags: feature flag states written to disk: yes
hunter-rabbitmq     | 2020-01-17 10:27:47.185 [info] <0.260.0> ra: meta data store initialised. 0 record(s) recovered
hunter-rabbitmq     | 2020-01-17 10:27:47.194 [info] <0.265.0> WAL: recovering []
hunter-rabbitmq     | 2020-01-17 10:27:47.208 [info] <0.269.0> 
hunter-rabbitmq     |  Starting RabbitMQ 3.8.1 on Erlang 22.1.5
hunter-rabbitmq     |  Copyright (c) 2007-2019 Pivotal Software, Inc.

**Comment by bsmali4** [comment]
这个docker使用本身的问题，你下次重启之前docker-compose down。
