### ISSUE TITLE
console里能看到日志，但是全部都是“net::ERR_CONNECTION_REFUSED”报错

### ISSUE THREAD

**Issue by nibiwodong** [ztosec/hunter#6]
我修改了docker-compose文件的IP，默认是127.0.0.1，我改成了自己服务器的IP地址，可以成功启动。
此时安装chrome插件，任务可以同步下来，console里也有日志打印出来。
但是所有日志，都会提示“net::ERR_CONNECTION_REFUSED”，并且后台看不到扫描URL的日志。
![image](https://user-images.githubusercontent.com/17465789/72402754-1c1f0c00-378b-11ea-9569-92dc3c1be33d.png)
报错是127.0.0.1访问的问题，我手工访问这个地址，把IP改为自己服务器IP，提示“Method Not Allowed”
http://127.0.0.1:8888/api/v1/user/task/1/url/task_access_key/3e1d9575219eacedad01c45007ca262738ae751f572bc078045007905858f2517bafb25932de58b6c0f5e3a385e594ef0d624cf5a746db2913da6e48b19311d4b96d17c01cdd170ebd82e4208d6f807e4d716acbb9301eba4f5de86fa4b0ae23
![image](https://user-images.githubusercontent.com/17465789/72402826-54bee580-378b-11ea-8e5e-9b0f900872f2.png)

请问是哪里配置的不对吗？

**Comment by hack2012** [comment]
安装插件之前需要修改插件common.js里面的127为自己服务器ip地址，你看一下文档里面有的。

**Comment by nibiwodong** [comment]
问题已经解决。
我是先安装chrome插件，再手工修改common.js。以为会实时生效，实际上没有生效。
我卸载chrome插件，重新安装，问题解决了。
感谢！！！！！！
